apiVersion: v1
kind: Service
metadata:
  name: risk-sim
  namespace: risk-sim
spec:
  selector:
    app: risk-sim
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080   # http://<R430-node-ip>:30080
  type: NodePort
