#!/bin/bash
# Pin requirements.txt to the exact versions running in the (working) container.
# Run ON THE SERVER while the stack is healthy:  bash deploy/pin-requirements.sh
# Then commit the updated requirements.txt.
#
# Why: unpinned '>=' requirements caused the Starlette 0.47 TemplateResponse
# breakage — the same code built differently depending on the install date.
# requirements.in keeps the human-readable list of DIRECT dependencies;
# requirements.txt becomes the frozen, reproducible install set.
set -euo pipefail
cd "$(dirname "$0")/.."

echo "Freezing package versions from the running web container..."
{
  echo "# ── Frozen dependency set ─────────────────────────────────────────────"
  echo "# Generated by deploy/pin-requirements.sh on $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "# Direct dependencies are documented in requirements.in."
  echo "# To upgrade: edit requirements.in, test, then re-run this script."
  docker compose exec -T web pip freeze --exclude-editable
} > requirements.txt

echo ""
echo "requirements.txt pinned ($(grep -c '==' requirements.txt) packages)."
echo "Review, then:  git add requirements.txt requirements.in && git commit -m 'Pin dependencies' && git push"
